In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_afname = pd.read_csv('data/afname-2024.csv', sep=';')
df_afname.head()

,Van (datum),Van (tijdstip),Tot (datum),Tot (tijdstip),EAN-code,Meter,Metertype,Register,Volume,Eenheid,Validatiestatus,Omschrijving
0,01-01-2024,00:00:00,01-01-2024,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,625",kWh,Gevalideerd,NaN
1,01-01-2024,00:00:00,01-01-2024,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Reactief,"0,000",kVArh,Gevalideerd,NaN
2,01-01-2024,00:00:00,01-01-2024,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Capacitief,"3,750",kVArh,Gevalideerd,NaN
3,01-01-2024,00:00:00,01-01-2024,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Inductief,"0,000",kVArh,Gevalideerd,NaN
4,01-01-2024,00:15:00,01-01-2024,00:30:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,625",kWh,Gevalideerd,NaN

In [3]:
df_afname_2025 = pd.read_csv('data/Historiek_afname_elektriciteit_541448800000018463_20250101_20260101_kwartiertotalen.csv', sep=';')
df_afname_2025.head()

,Van (datum),Van (tijdstip),Tot (datum),Tot (tijdstip),EAN-code,Meter,Metertype,Register,Volume,Eenheid,Validatiestatus,Omschrijving
0,01/01/2025,00:00:00,01/01/2025,00:15:00,541448800000018463,NaN,AMR-meter,Afname Actief,10,kWh,Gevalideerd,NaN
1,01/01/2025,00:00:00,01/01/2025,00:15:00,541448800000018463,NaN,AMR-meter,Afname Reactief,"1,41",kVArh,Gevalideerd,NaN
2,01/01/2025,00:00:00,01/01/2025,00:15:00,541448800000018463,NaN,AMR-meter,Afname Capacitief,"6,25",kVArh,Gevalideerd,NaN
3,01/01/2025,00:00:00,01/01/2025,00:15:00,541448800000018463,NaN,AMR-meter,Afname Inductief,0,kVArh,Gevalideerd,NaN
4,01/01/2025,00:15:00,01/01/2025,00:30:00,541448800000018463,NaN,AMR-meter,Afname Actief,"9,375",kWh,Gevalideerd,NaN

In [2]:
df_afname_2026 = pd.read_csv('data/data 2026/afname_2026.csv', sep=';')
df_afname_2026.head()

,Van (datum),Van (tijdstip),Tot (datum),Tot (tijdstip),EAN-code,Meter,Metertype,Register,Volume,Eenheid,Validatiestatus,Omschrijving
0,01-01-2026,00:00:00,01-01-2026,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN
1,01-01-2026,00:00:00,01-01-2026,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Reactief,"0,000",kVArh,Gevalideerd,NaN
2,01-01-2026,00:00:00,01-01-2026,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Capacitief,"3,750",kVArh,Gevalideerd,NaN
3,01-01-2026,00:00:00,01-01-2026,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Inductief,"0,000",kVArh,Gevalideerd,NaN
4,01-01-2026,00:15:00,01-01-2026,00:30:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN

In [3]:
#filter op afname actief (staat in kolom Register)
df_afname = df_afname[df_afname['Register'] == "Afname Actief"]
df_afname.head()

,Van (datum),Van (tijdstip),Tot (datum),Tot (tijdstip),EAN-code,Meter,Metertype,Register,Volume,Eenheid,Validatiestatus,Omschrijving
0,01-01-2024,00:00:00,01-01-2024,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,625",kWh,Gevalideerd,NaN
4,01-01-2024,00:15:00,01-01-2024,00:30:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,625",kWh,Gevalideerd,NaN
8,01-01-2024,00:30:00,01-01-2024,00:45:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"11,875",kWh,Gevalideerd,NaN
12,01-01-2024,00:45:00,01-01-2024,01:00:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"13,750",kWh,Gevalideerd,NaN
16,01-01-2024,01:00:00,01-01-2024,01:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"14,375",kWh,Gevalideerd,NaN

In [4]:
#filter op afname actief (staat in kolom Register)
df_afname_2025 = df_afname_2025[df_afname_2025['Register'] == "Afname Actief"]
df_afname_2025.head()

,Van (datum),Van (tijdstip),Tot (datum),Tot (tijdstip),EAN-code,Meter,Metertype,Register,Volume,Eenheid,Validatiestatus,Omschrijving
0,01/01/2025,00:00:00,01/01/2025,00:15:00,541448800000018463,NaN,AMR-meter,Afname Actief,10,kWh,Gevalideerd,NaN
4,01/01/2025,00:15:00,01/01/2025,00:30:00,541448800000018463,NaN,AMR-meter,Afname Actief,"9,375",kWh,Gevalideerd,NaN
8,01/01/2025,00:30:00,01/01/2025,00:45:00,541448800000018463,NaN,AMR-meter,Afname Actief,"11,875",kWh,Gevalideerd,NaN
12,01/01/2025,00:45:00,01/01/2025,01:00:00,541448800000018463,NaN,AMR-meter,Afname Actief,"11,875",kWh,Gevalideerd,NaN
16,01/01/2025,01:00:00,01/01/2025,01:15:00,541448800000018463,NaN,AMR-meter,Afname Actief,"11,25",kWh,Gevalideerd,NaN

In [3]:
#filter op afname actief (staat in kolom Register)
df_afname_2026 = df_afname_2026[df_afname_2026['Register'] == "Afname Actief"]
df_afname_2026.head()

,Van (datum),Van (tijdstip),Tot (datum),Tot (tijdstip),EAN-code,Meter,Metertype,Register,Volume,Eenheid,Validatiestatus,Omschrijving
0,01-01-2026,00:00:00,01-01-2026,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN
4,01-01-2026,00:15:00,01-01-2026,00:30:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN
8,01-01-2026,00:30:00,01-01-2026,00:45:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN
12,01-01-2026,00:45:00,01-01-2026,01:00:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN
16,01-01-2026,01:00:00,01-01-2026,01:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN

In [5]:
df_afname['datetime'] = pd.to_datetime(
    df_afname['Van (datum)'].astype(str) + ' ' + df_afname['Van (tijdstip)'].astype(str),
    dayfirst=True
)

In [5]:
df_afname_2025['datetime'] = pd.to_datetime(
    df_afname_2025['Van (datum)'].astype(str) + ' ' + df_afname_2025['Van (tijdstip)'].astype(str),
    dayfirst=True
)

In [4]:
df_afname_2026['datetime'] = pd.to_datetime(
    df_afname_2026['Van (datum)'].astype(str) + ' ' + df_afname_2026['Van (tijdstip)'].astype(str),
    dayfirst=True
)

In [6]:
df_afname.head()

,Van (datum),Van (tijdstip),Tot (datum),Tot (tijdstip),EAN-code,Meter,Metertype,Register,Volume,Eenheid,Validatiestatus,Omschrijving,datetime
0,01-01-2024,00:00:00,01-01-2024,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,625",kWh,Gevalideerd,NaN,2024-01-01 00:00:00
4,01-01-2024,00:15:00,01-01-2024,00:30:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,625",kWh,Gevalideerd,NaN,2024-01-01 00:15:00
8,01-01-2024,00:30:00,01-01-2024,00:45:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"11,875",kWh,Gevalideerd,NaN,2024-01-01 00:30:00
12,01-01-2024,00:45:00,01-01-2024,01:00:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"13,750",kWh,Gevalideerd,NaN,2024-01-01 00:45:00
16,01-01-2024,01:00:00,01-01-2024,01:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"14,375",kWh,Gevalideerd,NaN,2024-01-01 01:00:00

In [6]:
df_afname_2025.head()

,Van (datum),Van (tijdstip),Tot (datum),Tot (tijdstip),EAN-code,Meter,Metertype,Register,Volume,Eenheid,Validatiestatus,Omschrijving,datetime
0,01/01/2025,00:00:00,01/01/2025,00:15:00,541448800000018463,NaN,AMR-meter,Afname Actief,10,kWh,Gevalideerd,NaN,2025-01-01 00:00:00
4,01/01/2025,00:15:00,01/01/2025,00:30:00,541448800000018463,NaN,AMR-meter,Afname Actief,"9,375",kWh,Gevalideerd,NaN,2025-01-01 00:15:00
8,01/01/2025,00:30:00,01/01/2025,00:45:00,541448800000018463,NaN,AMR-meter,Afname Actief,"11,875",kWh,Gevalideerd,NaN,2025-01-01 00:30:00
12,01/01/2025,00:45:00,01/01/2025,01:00:00,541448800000018463,NaN,AMR-meter,Afname Actief,"11,875",kWh,Gevalideerd,NaN,2025-01-01 00:45:00
16,01/01/2025,01:00:00,01/01/2025,01:15:00,541448800000018463,NaN,AMR-meter,Afname Actief,"11,25",kWh,Gevalideerd,NaN,2025-01-01 01:00:00

In [5]:
df_afname_2026.head()

,Van (datum),Van (tijdstip),Tot (datum),Tot (tijdstip),EAN-code,Meter,Metertype,Register,Volume,Eenheid,Validatiestatus,Omschrijving,datetime
0,01-01-2026,00:00:00,01-01-2026,00:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN,2026-01-01 00:00:00
4,01-01-2026,00:15:00,01-01-2026,00:30:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN,2026-01-01 00:15:00
8,01-01-2026,00:30:00,01-01-2026,00:45:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN,2026-01-01 00:30:00
12,01-01-2026,00:45:00,01-01-2026,01:00:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN,2026-01-01 00:45:00
16,01-01-2026,01:00:00,01-01-2026,01:15:00,"=""541448800000018463""",NaN,AMR-meter,Afname Actief,"10,000",kWh,Gevalideerd,NaN,2026-01-01 01:00:00

In [10]:
#verwijder allekollomen behalve volume en datetime
df_afname = df_afname[['datetime', 'Volume']]
df_afname.head()

             datetime  Volume
0 2024-01-01 00:00:00  10,625
1 2024-01-01 00:15:00  10,625
2 2024-01-01 00:30:00  11,875
3 2024-01-01 00:45:00  13,750
4 2024-01-01 01:00:00  14,375

In [7]:
#verwijder allekollomen behalve volume en datetime
df_afname_2025 = df_afname_2025[['datetime', 'Volume']]
df_afname_2025.head()

              datetime  Volume
0  2025-01-01 00:00:00      10
4  2025-01-01 00:15:00   9,375
8  2025-01-01 00:30:00  11,875
12 2025-01-01 00:45:00  11,875
16 2025-01-01 01:00:00   11,25

In [7]:
#verwijder allekollomen behalve volume en datetime
df_afname_2026 = df_afname_2026[['datetime', 'Volume']]
df_afname_2026.head()

              datetime  Volume
0  2026-01-01 00:00:00  10,000
4  2026-01-01 00:15:00  10,000
8  2026-01-01 00:30:00  10,000
12 2026-01-01 00:45:00  10,000
16 2026-01-01 01:00:00  10,000

In [11]:
df_afname.to_excel('data/afname-2024.xlsx', index=False)

## Injectie

In [29]:
df_injectie = pd.read_excel('injectie_2024.xlsx')
df_injectie.head()

                  Date  Energie (kWh)
0  2024-01-01 00:00:00            0.0
1  2024-01-01 00:15:00            0.0
2  2024-01-01 00:30:00            0.0
3  2024-01-01 00:45:00            0.0
4  2024-01-01 01:00:00            0.0

In [30]:
df_injectie_2025 = pd.read_excel('injectie_2025.xlsx')
df_injectie_2025.head()

                 Date  Energie (kWh)
0 2025-01-01 01:00:00            0.0
1 2025-01-01 01:15:00            0.0
2 2025-01-01 01:30:00            0.0
3 2025-01-01 01:45:00            0.0
4 2025-01-01 02:00:00            0.0

In [8]:
df_injectie_2026 = pd.read_csv('data/data 2026/injectie_2026.csv', sep=';')
df_injectie_2026.head()

,EAN,Datum en tijdstip (UTC),Datum en tijdstip (Europa/Brussel),Energie (kWh)
0,EAN541448860008243540,31/12/2024 23:00,1/01/2025 0:00,0
1,EAN541448860008243540,31/12/2024 23:15,1/01/2025 0:15,0
2,EAN541448860008243540,31/12/2024 23:30,1/01/2025 0:30,0
3,EAN541448860008243540,31/12/2024 23:45,1/01/2025 0:45,0
4,EAN541448860008243540,1/01/2025 0:00,1/01/2025 1:00,0

In [21]:
#delete EAN Datum en tijdstip (UTC) kolom
# df_injectie_2026 = df_injectie_2026.drop(columns=['Datum en tijdstip (UTC)'])
# df_injectie_2026 = df_injectie_2026.drop(columns=['EAN'])
df_injectie_2026 = df_injectie_2026.drop(columns=['Datum en tijdstip (Europa/Brussel)'])
df_injectie_2026.head()

  Energie (kWh)            datetime
0             0 2025-01-01 00:00:00
1             0 2025-01-01 00:15:00
2             0 2025-01-01 00:30:00
3             0 2025-01-01 00:45:00
4             0 2025-01-01 01:00:00

In [22]:
#zet datetime kolom als eerste kolom
cols = df_injectie_2026.columns.tolist()
cols = cols[-1:] + cols[:-1]
df_injectie_2026 = df_injectie_2026[cols]
df_injectie_2026.head()

             datetime Energie (kWh)
0 2025-01-01 00:00:00             0
1 2025-01-01 00:15:00             0
2 2025-01-01 00:30:00             0
3 2025-01-01 00:45:00             0
4 2025-01-01 01:00:00             0

In [ ]:
df_afname['datetime'] = pd.to_datetime(df_afname['datetime'], dayfirst=True)
df_injectie['datetime'] = pd.to_datetime(df_injectie['Date'])

In [32]:
df_afname_2025['datetime'] = pd.to_datetime(df_afname_2025['datetime'], dayfirst=True)
df_injectie_2025['datetime'] = pd.to_datetime(df_injectie_2025['Date'], dayfirst=True)

In [24]:
df_afname_2026['datetime'] = pd.to_datetime(df_afname_2026['datetime'], dayfirst=True)
df_injectie_2026['datetime'] = pd.to_datetime(df_injectie_2026['datetime'], dayfirst=True)

In [25]:
df_injectie_2026.head()

             datetime Energie (kWh)
0 2025-01-01 00:00:00             0
1 2025-01-01 00:15:00             0
2 2025-01-01 00:30:00             0
3 2025-01-01 00:45:00             0
4 2025-01-01 01:00:00             0

In [16]:
df = pd.merge(
    df_afname,
    df_injectie,
    on='datetime',
    how='outer',
    suffixes=('_afname', '_injectie')
)

In [42]:
df_2025 = pd.merge(
    df_afname_2025,
    df_injectie_2025,
    on='datetime',
    how='outer',
    suffixes=('_afname', '_injectie')
)

In [51]:
df_2026 = pd.merge(
    df_afname_2026,
    df_injectie_2026,
    on='datetime',
    how='outer',
    suffixes=('_afname', '_injectie')
)

In [44]:
df_2026.head()

             datetime Volume Energie (kWh)
0 2025-01-01 00:00:00    NaN             0
1 2025-01-01 00:15:00    NaN             0
2 2025-01-01 00:30:00    NaN             0
3 2025-01-01 00:45:00    NaN             0
4 2025-01-01 01:00:00    NaN             0

In [17]:
df[df.duplicated(subset=['datetime'], keep=False)]

                 datetime  Volume                 Date  Energie (kWh)
28804 2024-10-27 02:00:00  18,125  2024-10-27 02:00:00            0.0
28805 2024-10-27 02:00:00  18,125  2024-10-27 02:00:00            0.0
28806 2024-10-27 02:00:00  18,125  2024-10-27 02:00:00            0.0
28807 2024-10-27 02:00:00  18,125  2024-10-27 02:00:00            0.0
28808 2024-10-27 02:15:00  18,125  2024-10-27 02:15:00            0.0
28809 2024-10-27 02:15:00  18,125  2024-10-27 02:15:00            0.0
28810 2024-10-27 02:15:00  18,125  2024-10-27 02:15:00            0.0
28811 2024-10-27 02:15:00  18,125  2024-10-27 02:15:00            0.0
28812 2024-10-27 02:30:00  17,500  2024-10-27 02:30:00            0.0
28813 2024-10-27 02:30:00  17,500  2024-10-27 02:30:00            0.0
28814 2024-10-27 02:30:00  17,500  2024-10-27 02:30:00            0.0
28815 2024-10-27 02:30:00  17,500  2024-10-27 02:30:00            0.0
28816 2024-10-27 02:45:00  17,500  2024-10-27 02:45:00            0.0
28817 2024-10-27 02:45:00  17,500  2024-10-27 02:45:00            0.0
28818 2024-10-27 02:45:00  18,125  2024-10-27 02:45:00            0.0
28819 2024-10-27 02:45:00  18,125  2024-10-27 02:45:00            0.0

In [43]:
df_2025[df_2025.duplicated(subset=['datetime'], keep=False)]

                 datetime  Volume Date  Energie (kWh)
28616 2025-10-26 02:00:00    17,5  NaT            NaN
28617 2025-10-26 02:00:00  20,625  NaT            NaN
28618 2025-10-26 02:15:00  16,875  NaT            NaN
28619 2025-10-26 02:15:00  20,625  NaT            NaN
28620 2025-10-26 02:30:00  19,375  NaT            NaN
28621 2025-10-26 02:30:00  19,375  NaT            NaN
28622 2025-10-26 02:45:00   21,25  NaT            NaN
28623 2025-10-26 02:45:00  19,375  NaT            NaN

In [52]:
df_2026[df_2026.duplicated(subset=['datetime'], keep=False)]

                 datetime Volume Energie (kWh)
28612 2025-10-26 02:00:00    NaN             0
28613 2025-10-26 02:00:00    NaN             0
28614 2025-10-26 02:15:00    NaN             0
28615 2025-10-26 02:15:00    NaN             0
28616 2025-10-26 02:30:00    NaN             0
28617 2025-10-26 02:30:00    NaN             0
28618 2025-10-26 02:45:00    NaN             0
28619 2025-10-26 02:45:00    NaN             0

In [ ]:
df = df.drop_duplicates(subset=['datetime'], keep='first')

In [44]:
df_2025 = df_2025.drop_duplicates(subset=['datetime'], keep='first')

In [53]:
df_2026 = df_2026.drop_duplicates(subset=['datetime'], keep='first')

In [54]:
df_2026.head()

             datetime Volume Energie (kWh)
0 2025-01-01 00:00:00    NaN             0
1 2025-01-01 00:15:00    NaN             0
2 2025-01-01 00:30:00    NaN             0
3 2025-01-01 00:45:00    NaN             0
4 2025-01-01 01:00:00    NaN             0

In [55]:
# delete allerijen van 2025
df_2026 = df_2026[df_2026['datetime'].dt.year != 2025]
df_2026.head()

                 datetime  Volume Energie (kWh)
35040 2026-01-01 00:00:00  10,000             0
35041 2026-01-01 00:15:00  10,000             0
35042 2026-01-01 00:30:00  10,000             0
35043 2026-01-01 00:45:00  10,000             0
35044 2026-01-01 01:00:00  10,000             0

In [56]:
#zet Volume & Energie (kWh) kolommen om naar float
df_2026 = df_2026.rename(columns={'Energie (kWh)': 'injectie_kwh'})
df_2026 = df_2026.rename(columns={'Volume': 'afname_kwh'})
df_2026.head()

                 datetime afname_kwh injectie_kwh
35040 2026-01-01 00:00:00     10,000            0
35041 2026-01-01 00:15:00     10,000            0
35042 2026-01-01 00:30:00     10,000            0
35043 2026-01-01 00:45:00     10,000            0
35044 2026-01-01 01:00:00     10,000            0

In [57]:
df_2026['afname_kwh'] = (
    df_2026['afname_kwh']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

df_2026['injectie_kwh'] = (
    df_2026['injectie_kwh']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

df_2026['afname_kwh'] = pd.to_numeric(df_2026['afname_kwh'], errors='coerce')
df_2026['injectie_kwh'] = pd.to_numeric(df_2026['injectie_kwh'], errors='coerce')

In [58]:
df_2026.head()

                 datetime  afname_kwh  injectie_kwh
35040 2026-01-01 00:00:00        10.0           0.0
35041 2026-01-01 00:15:00        10.0           0.0
35042 2026-01-01 00:30:00        10.0           0.0
35043 2026-01-01 00:45:00        10.0           0.0
35044 2026-01-01 01:00:00        10.0           0.0

In [45]:
full_range = pd.date_range(
    start=df['datetime'].min(),
    end=df['datetime'].max(),
    freq='15T'
)

missing = full_range.difference(df['datetime'])

print("Missing intervals:", len(missing))

NameError: name 'df' is not defined

In [46]:
full_range = pd.date_range(
    start=df_2025['datetime'].min(),
    end=df_2025['datetime'].max(),
    freq='15T'
)

missing = full_range.difference(df_2025['datetime'])

print("Missing intervals:", len(missing))

Missing intervals: 0

C:\Users\ilias\AppData\Local\Temp\ipykernel_4836\1795473552.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  full_range = pd.date_range(

In [59]:
full_range = pd.date_range(
    start=df_2026['datetime'].min(),
    end=df_2026['datetime'].max(),
    freq='15T'
)

missing = full_range.difference(df_2026['datetime'])

print("Missing intervals:", len(missing))

Missing intervals: 4

C:\Users\ilias\AppData\Local\Temp\ipykernel_29300\3634238181.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  full_range = pd.date_range(

In [37]:
print(missing)

DatetimeIndex([], dtype='datetime64[ns]', freq='15min')

In [21]:
df = df.set_index('datetime').asfreq('15min')
df = df.interpolate().reset_index()

C:\Users\ilias\AppData\Local\Temp\ipykernel_39176\3018338381.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df = df.interpolate().reset_index()

In [60]:
df_2026 = df_2026.set_index('datetime').asfreq('15min')
df_2026 = df_2026.interpolate().reset_index()

In [22]:
full_range = pd.date_range(
    start=df['datetime'].min(),
    end=df['datetime'].max(),
    freq='15T'
)

missing = full_range.difference(df['datetime'])

print("Missing intervals:", len(missing))

Missing intervals: 0

C:\Users\ilias\AppData\Local\Temp\ipykernel_39176\3210198150.py:1: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  full_range = pd.date_range(

In [24]:
df.head()

             datetime  Volume                 Date  Energie (kWh)
0 2024-01-01 00:00:00  10,625  2024-01-01 00:00:00            0.0
1 2024-01-01 00:15:00  10,625  2024-01-01 00:15:00            0.0
2 2024-01-01 00:30:00  11,875  2024-01-01 00:30:00            0.0
3 2024-01-01 00:45:00  13,750  2024-01-01 00:45:00            0.0
4 2024-01-01 01:00:00  14,375  2024-01-01 01:00:00            0.0

In [ ]:
df_2025.head()

             datetime  Volume                Date  Energie (kWh)
0 2025-01-01 00:00:00      10                 NaT            NaN
1 2025-01-01 00:15:00   9,375                 NaT            NaN
2 2025-01-01 00:30:00  11,875                 NaT            NaN
3 2025-01-01 00:45:00  11,875                 NaT            NaN
4 2025-01-01 01:00:00   11,25 2025-01-01 01:00:00            0.0

In [48]:
#verwijder Date & verander energie (kWh) naar injectie_kwh
df = df.drop(columns=['Date'])
df = df.rename(columns={'Energie (kWh)': 'injectie_kwh'})
df = df.rename(columns={'Volume': 'afname_kwh'})
df.head()

NameError: name 'df' is not defined

In [49]:
#verwijder Date & verander energie (kWh) naar injectie_kwh
df_2025 = df_2025.drop(columns=['Date'])
df_2025 = df_2025.rename(columns={'Energie (kWh)': 'injectie_kwh'})
df_2025 = df_2025.rename(columns={'Volume': 'afname_kwh'})
df_2025.head()

             datetime afname_kwh  injectie_kwh
0 2025-01-01 00:00:00         10           NaN
1 2025-01-01 00:15:00      9,375           NaN
2 2025-01-01 00:30:00     11,875           NaN
3 2025-01-01 00:45:00     11,875           NaN
4 2025-01-01 01:00:00      11,25           0.0

In [35]:
#verwijder Date & verander energie (kWh) naar injectie_kwh
df_2026 = df_2026.rename(columns={'Energie (kWh)': 'injectie_kwh'})
df_2026 = df_2026.rename(columns={'Volume': 'afname_kwh'})
df_2026.head()

             datetime  afname_kwh  injectie_kwh
0 2026-01-01 00:00:00         NaN           0.0
1 2026-01-01 00:15:00         NaN           0.0
2 2026-01-01 00:30:00         NaN           0.0
3 2026-01-01 00:45:00         NaN           0.0
4 2026-01-01 01:00:00         NaN           0.0

In [26]:
df.isnull().sum()

datetime        0
afname_kwh      4
injectie_kwh    0
dtype: int64

In [50]:
df_2025.isnull().sum()

datetime           0
afname_kwh         4
injectie_kwh    6724
dtype: int64

In [61]:
df_2026.isnull().sum()

datetime        0
afname_kwh      0
injectie_kwh    0
dtype: int64

In [54]:
#fill injectie_kwh null values with 0
df_2025['injectie_kwh'] = df_2025['injectie_kwh'].fillna(0)
df_2025['afname_kwh'] = df_2025['afname_kwh'].fillna(0)

In [55]:
df_2025.isnull().sum()

datetime        0
afname_kwh      0
injectie_kwh    0
dtype: int64

In [27]:
#interpolatie voor afname_kwh
df['afname_kwh'] = df['afname_kwh'].interpolate(method='linear')

df.head()

C:\Users\ilias\AppData\Local\Temp\ipykernel_39176\2134232960.py:2: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df['afname_kwh'] = df['afname_kwh'].interpolate(method='linear')

             datetime afname_kwh  injectie_kwh
0 2024-01-01 00:00:00     10,625           0.0
1 2024-01-01 00:15:00     10,625           0.0
2 2024-01-01 00:30:00     11,875           0.0
3 2024-01-01 00:45:00     13,750           0.0
4 2024-01-01 01:00:00     14,375           0.0

In [51]:
#interpolatie voor afname_kwh
df_2025['afname_kwh'] = df_2025['afname_kwh'].interpolate(method='linear')

df_2025.head()

C:\Users\ilias\AppData\Local\Temp\ipykernel_4836\176891947.py:2: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_2025['afname_kwh'] = df_2025['afname_kwh'].interpolate(method='linear')

             datetime afname_kwh  injectie_kwh
0 2025-01-01 00:00:00         10           NaN
1 2025-01-01 00:15:00      9,375           NaN
2 2025-01-01 00:30:00     11,875           NaN
3 2025-01-01 00:45:00     11,875           NaN
4 2025-01-01 01:00:00      11,25           0.0

In [58]:
print(sum(df_2025['injectie_kwh']))
df_2025.head()

364124.48

             datetime afname_kwh  injectie_kwh
0 2025-01-01 00:00:00         10           0.0
1 2025-01-01 00:15:00      9,375           0.0
2 2025-01-01 00:30:00     11,875           0.0
3 2025-01-01 00:45:00     11,875           0.0
4 2025-01-01 01:00:00      11,25           0.0

In [ ]:
#save df_2026

In [59]:
df_productie = pd.read_excel('data/combined_electricity_consumption_2025.xlsx')
df_productie.head()

                Datum   verbruik  productie
0 2025-01-01 00:00:00  33.153172        0.0
1 2025-01-01 00:15:00  33.143776        0.0
2 2025-01-01 00:30:00  39.696608        0.0
3 2025-01-01 00:45:00  41.295508        0.0
4 2025-01-01 01:00:00  40.903996        0.0

In [66]:
df_productie_2026 = pd.read_csv('data/data 2026/productie_2026.csv', sep=';')
df_productie_2026.head()

,EAN,Datum en tijdstip (UTC),Datum en tijdstip (Europa/Brussel),Energie (kWh)
0,EAN541454897100015059,2024-12-31 23:00:00,2025-01-01 00:00:00,0.0125
1,EAN541454897100015059,2024-12-31 23:15:00,2025-01-01 00:15:00,0.0250
2,EAN541454897100015059,2024-12-31 23:30:00,2025-01-01 00:30:00,0.0250
3,EAN541454897100015059,2024-12-31 23:45:00,2025-01-01 00:45:00,0.0250
4,EAN541454897100015059,2025-01-01 00:00:00,2025-01-01 01:00:00,0.0250

In [67]:
#verwijder EAN kolom & Datum en tijdstip (UTC) kolom
df_productie_2026 = df_productie_2026.drop(columns=['EAN'])
df_productie_2026 = df_productie_2026.drop(columns=['Datum en tijdstip (UTC)'])
df_productie_2026.head()

  Datum en tijdstip (Europa/Brussel)  Energie (kWh)
0                2025-01-01 00:00:00         0.0125
1                2025-01-01 00:15:00         0.0250
2                2025-01-01 00:30:00         0.0250
3                2025-01-01 00:45:00         0.0250
4                2025-01-01 01:00:00         0.0250

In [69]:
#Verander Datum en tijdstip (UTC) naar datetime
df_productie_2026['datetime'] = pd.to_datetime(df_productie_2026['Datum en tijdstip (Europa/Brussel)'])
df_productie_2026.head()

  Datum en tijdstip (Europa/Brussel)  Energie (kWh)            datetime
0                2025-01-01 00:00:00         0.0125 2025-01-01 00:00:00
1                2025-01-01 00:15:00         0.0250 2025-01-01 00:15:00
2                2025-01-01 00:30:00         0.0250 2025-01-01 00:30:00
3                2025-01-01 00:45:00         0.0250 2025-01-01 00:45:00
4                2025-01-01 01:00:00         0.0250 2025-01-01 01:00:00

In [70]:
df_productie_2026 = df_productie_2026.drop(columns=['Datum en tijdstip (Europa/Brussel)'])
df_productie_2026.head()

   Energie (kWh)            datetime
0         0.0125 2025-01-01 00:00:00
1         0.0250 2025-01-01 00:15:00
2         0.0250 2025-01-01 00:30:00
3         0.0250 2025-01-01 00:45:00
4         0.0250 2025-01-01 01:00:00

In [71]:
#zet datetime kolom op eerste kolom
cols = df_productie_2026.columns.tolist()
cols = cols[-1:] + cols[:-1]
df_productie_2026 = df_productie_2026[cols]
df_productie_2026.head()

             datetime  Energie (kWh)
0 2025-01-01 00:00:00         0.0125
1 2025-01-01 00:15:00         0.0250
2 2025-01-01 00:30:00         0.0250
3 2025-01-01 00:45:00         0.0250
4 2025-01-01 01:00:00         0.0250

In [72]:
#verwijder alle rijen met 2025
df_productie_2026 = df_productie_2026[df_productie_2026['datetime'].dt.year != 2025]
df_productie_2026.head()

                 datetime  Energie (kWh)
34940 2026-01-01 00:00:00         0.0250
34941 2026-01-01 00:15:00         0.0250
34942 2026-01-01 00:30:00         0.0125
34943 2026-01-01 00:45:00         0.0250
34944 2026-01-01 01:00:00         0.0250

In [73]:
#verander Energie (kWh) naar productie_kwh
df_productie_2026 = df_productie_2026.rename(columns={'Energie (kWh)': 'productie_kwh'})
df_productie_2026.head()

                 datetime  productie_kwh
34940 2026-01-01 00:00:00         0.0250
34941 2026-01-01 00:15:00         0.0250
34942 2026-01-01 00:30:00         0.0125
34943 2026-01-01 00:45:00         0.0250
34944 2026-01-01 01:00:00         0.0250

In [74]:
#merg met df_2026
df_2026 = pd.merge(
    df_2026,
    df_productie_2026,
    on='datetime',
    how='outer',
    suffixes=('_afname_injectie', '_productie')
)

In [75]:
df_2026.head()

             datetime  afname_kwh  injectie_kwh  productie_kwh
0 2026-01-01 00:00:00        10.0           0.0         0.0250
1 2026-01-01 00:15:00        10.0           0.0         0.0250
2 2026-01-01 00:30:00        10.0           0.0         0.0125
3 2026-01-01 00:45:00        10.0           0.0         0.0250
4 2026-01-01 01:00:00        10.0           0.0         0.0250

In [77]:
df_2026.isnull().sum()

datetime         0
afname_kwh       0
injectie_kwh     0
productie_kwh    4
dtype: int64

In [78]:
#fill null values in productie_kwh next value downwards
df_2026['productie_kwh'] = df_2026['productie_kwh'].fillna(method='bfill')
df_2026.isnull().sum()

C:\Users\ilias\AppData\Local\Temp\ipykernel_29300\3610805497.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_2026['productie_kwh'] = df_2026['productie_kwh'].fillna(method='bfill')

datetime         0
afname_kwh       0
injectie_kwh     0
productie_kwh    0
dtype: int64

In [60]:
#Zet productie om van kw naar kwh
df_productie['productie_kwh'] = df_productie['productie'] * 0.25
df_productie = df_productie.drop(columns=['productie'])

In [61]:
#zet alles onder 0 bij productie_kwh op 0
df_productie['productie_kwh'] = df_productie['productie_kwh'].apply(lambda x: max(x, 0))
df_productie.head()

                Datum   verbruik  productie_kwh
0 2025-01-01 00:00:00  33.153172            0.0
1 2025-01-01 00:15:00  33.143776            0.0
2 2025-01-01 00:30:00  39.696608            0.0
3 2025-01-01 00:45:00  41.295508            0.0
4 2025-01-01 01:00:00  40.903996            0.0

In [62]:
#verwijder verbruik kolom
df_productie = df_productie.drop(columns=['verbruik'])

In [66]:
#voeg productie toe aan df
df_2025 = pd.merge(
    df_2025,
    df_productie[['Datum', 'productie_kwh']],
    left_on='datetime',
    right_on='Datum',
    how='left'
)
df_2025.head()

,datetime,afname_kwh,injectie_kwh,Datum,productie_kwh
0,2025-01-01 00:00:00,10,0.0,2025-01-01 00:00:00,0.0
1,2025-01-01 00:15:00,"9,375",0.0,2025-01-01 00:15:00,0.0
2,2025-01-01 00:30:00,"11,875",0.0,2025-01-01 00:30:00,0.0
3,2025-01-01 00:45:00,"11,875",0.0,2025-01-01 00:45:00,0.0
4,2025-01-01 01:00:00,"11,25",0.0,2025-01-01 01:00:00,0.0

In [68]:
#verwijder date
df_2025 = df_2025.drop(columns=['Datum'])

In [69]:
df_2025.head()

             datetime afname_kwh  injectie_kwh  productie_kwh
0 2025-01-01 00:00:00         10           0.0            0.0
1 2025-01-01 00:15:00      9,375           0.0            0.0
2 2025-01-01 00:30:00     11,875           0.0            0.0
3 2025-01-01 00:45:00     11,875           0.0            0.0
4 2025-01-01 01:00:00      11,25           0.0            0.0

In [70]:
full_range = pd.date_range(
    start=df_2025['datetime'].min(),
    end=df_2025['datetime'].max(),
    freq='15min'
)

In [72]:
missing = full_range.difference(df_2025['datetime'])

print("Missing intervals:", len(missing))

Missing intervals: 0

In [73]:
duplicates = df_2025[df_2025.duplicated(subset=['datetime'], keep=False)]

print("Duplicate rows:", len(duplicates))

Duplicate rows: 16

In [74]:
#verwijder duplicaten
df_2025 = df_2025.drop_duplicates(subset=['datetime'], keep='first')

In [76]:
df_2025['productie_kwh'] = df_2025['productie_kwh'].ffill().bfill()

In [77]:
df_2025.isnull().sum()

datetime         0
afname_kwh       0
injectie_kwh     0
productie_kwh    0
dtype: int64

In [78]:
df_2025.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35040 entries, 0 to 35047
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   datetime       35040 non-null  datetime64[ns]
 1   afname_kwh     35040 non-null  object
 2   injectie_kwh   35040 non-null  float64
 3   productie_kwh  35040 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 1.3+ MB

In [80]:
df_2025['afname_kwh'] = (
    df_2025['afname_kwh']
    .str.replace(',', '.', regex=False)
    .astype(float)
)

In [81]:
df_2025.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35040 entries, 0 to 35047
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   datetime       35040 non-null  datetime64[ns]
 1   afname_kwh     35036 non-null  float64
 2   injectie_kwh   35040 non-null  float64
 3   productie_kwh  35040 non-null  float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 1.3 MB

In [82]:
df_2025.to_excel('energie_orac_2025.xlsx', index=False)

In [80]:
df_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11520 entries, 0 to 11519
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   datetime       11520 non-null  datetime64[ns]
 1   afname_kwh     11520 non-null  float64
 2   injectie_kwh   11520 non-null  float64
 3   productie_kwh  11520 non-null  float64
dtypes: datetime64[ns](1), float64(3)
memory usage: 360.1 KB

In [79]:
df_2026.to_excel('energie_orac_2026.xlsx', index=False)